name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo wget -q https://downloads.lightbend.com/scala/2.13.7/scala-2.13.7.deb
          sudo dpkg -i scala-2.13.7.deb

      - name: Check versions
        run: |
          java -version
          scala -version

      - name: Run
        run: scala -deprecation day01.scala
